services:
  pycket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - wintermute
#   volumes:
#     - "./:/app/"
networks:
  wintermute:
    external: true
    name: wintermute
